### ISSUE TITLE
npm version 5 rejects trailing space in package.json "sauce-connect-tunnel " dependency

### ISSUE THREAD

**Issue by robbear** [bytbil/sauce-test-runner#2]
Using npm version 5 to `npm install` with a dependency on `sauce-test-runner` gives the following error:

`Invalid package name "sauce-connect-tunnel ": name cannot contain leading or trailing spaces; name can only contain URL-friendly characters`

The trailing space in "sauce-connect-tunnel " in the package.json file needs to be removed.

**Comment by seberik** [comment]
Thank you for reporting! This should now be fixed in v0.1.8.
