### ISSUE TITLE
QUESTION: gulp.start is deprecated, any good alternative?

### ISSUE THREAD

**Issue by caraya** [bytbil/sauce-test-runner#3]
Gulp has deprecated `gulp.start` without providing a replacement I can understand (see gulpjs/gulp#505 for some of the discussion). Since the API is deprecated and will be removed in Gulp 4 (whenever that releases) do you have a good alternative to use instead of `gulp.start`?

**Comment by seberik** [comment]
Managing complex build processes is quite cumbersome in gulp 3 and I decided that it was better to use a deprecated function than including another module (e.g. run-sequence). I would be surprised if they actually release gulp 4 anytime soon and if they do, then it should be straight forward replacing it with the new series and parallell functions.
